### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by eorroe** [mreq/sublime-select-all-by-current-scope#1]
I've had this package for months but never used it because I'm very confused on how to use this correctly. I know a video may be too much to ask for. Yet if you do have the time can you please provide one. OR a GIF

**Comment by mreq** [comment]
There's a GIF for you. It's from a [knitr](https://github.com/yihui/knitr) document. I go inside a chunk which contains embedded R code. Fire the plugin command, copy what's selected and paste it into a new file - voila I have all of the R code used in the document.

![image](http://i.imgur.com/zQlw1Tp.gif)
